apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi

spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
      annotations:
        date: +%H:%M:%S %d/%m/%y
    spec:
      containers:
        - name: webapi
          image: birzgalisn/forecast-webapi:main
          imagePullPolicy: Always
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: webapi
                  key: DB_CONNECTION_STRING
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: webapi
                  key: REDIS_CONNECTION_STRING
          resources:
            requests:
              cpu: 200m
              memory: 250Mi
          ports:
            - name: app
              containerPort: 4000
          livenessProbe:
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /ping
              port: app
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: webapi

spec:
  type: NodePort
  ports:
    - port: 4000
  selector:
    app: webapi

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webapi-ingress-route

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.forecast.niksbirzgalis.com`)
      kind: Rule
      services:
        - name: webapi
          port: 4000
          sticky:
            cookie:
              httpOnly: true
              name: webapi
              secure: true
  tls:
    certResolver: letsencrypt
