version: "3.8"

volumes:
  db:
  pgadmin:
  caddy_data:
  caddy_config:

networks:
  db_net:
  proxy_net:

x-next-common: &next-common
  image: forecast/next:latest
  build:
    context: ./client
    dockerfile: ./Dockerfile
  environment:
    NODE_ENV: production
    NEXT_PUBLIC_API_URL: https://api.forecast.localhost
  networks:
    - proxy_net
  depends_on:
    - api

x-api-common: &api-common
  image: forecast/api:latest
  build:
    context: ./api
    dockerfile: ./Dockerfile
  environment:
    DOTNET_ENVIRONMENT: Production
    DOTNET_URLS: http://+:4000
    WEATHER_API_KEY: ${WEATHER_API_KEY}
    OPEN_WEATHER_KEY: ${OPEN_WEATHER_KEY}
  networks:
    - db_net
    - proxy_net
  depends_on:
    - db

services:
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: forecast
      POSTGRES_PASSWORD: forecast
      POSTGRES_DB: forecast
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db_net

  pgadmin:
    image: dpage/pgadmin4:7.8
    environment:
      PGADMIN_DEFAULT_EMAIL: forecast@local.host
      PGADMIN_DEFAULT_PASSWORD: forecast
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - db_net
      - proxy_net
    depends_on:
      - db

  api:
    <<: *api-common
    hostname: api

  next1:
    <<: *next-common
    hostname: next1

  next2:
    <<: *next-common
    hostname: next2

  next3:
    <<: *next-common
    hostname: next3

  next4:
    <<: *next-common
    hostname: next4

  caddy:
    image: caddy:2.7.5-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy_net
    depends_on:
      - next1
      - next2
      - next3
      - next4
      - api
      - pgadmin
