volumes:
  pgadmin:

services:
  pgadmin:
    image: dpage/pgadmin4:8.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin:/var/lib/pgadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.forecast.$CNAME`)
      - traefik.http.routers.pgadmin.entrypoints=web
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
    networks:
      - db
      - proxy
