version: "3"

name: forecast-development

networks:
  db_net:
  proxy_net:

include:
  - ../common/db-compose.yaml
  - ../common/pgadmin-compose.yaml
  - ../common/caddy-compose.yaml

services:
  api:
    image: forecast/api:development
    build:
      context: ../../api
      dockerfile: ./Dockerfile
      target: builder
    command: dotnet watch --non-interactive
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=$DB_CONNECTION_STRING
      - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
    volumes:
      - ../../api:/App
    networks:
      - db_net
      - proxy_net
    depends_on:
      - db

  client:
    image: forecast/client:development
    build:
      context: ../../client
      dockerfile: ./Dockerfile
      target: installer
    command: pnpm dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
      - NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
      - NEXT_PUBLIC_OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
    volumes:
      - ../../client:/app
    networks:
      - proxy_net
    depends_on:
      - api
