name: forecast-production

include:
  - ../common/db-compose.yaml
  - ../common/redis-compose.yaml
  - ../common/pgadmin-compose.yaml
  - ../common/traefik-compose.yaml

services:
  webapi:
    image: birzgalisn/forecast-webapi:main
    environment:
      - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
      - DB_CONNECTION_STRING=$DB_CONNECTION_STRING
      - REDIS_CONNECTION_STRING=$REDIS_CONNECTION_STRING
    labels:
      - traefik.enable=true
      - traefik.http.routers.webapi.rule=Host(`api.forecast.$CNAME`)
      - traefik.http.routers.webapi.entrypoints=web
      - traefik.http.services.webapi.loadbalancer.server.port=4000
    networks:
      - db
      - redis
      - proxy
    depends_on:
      - db
      - redis

  next:
    image: birzgalisn/forecast-next:main
    environment:
      - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
    networks:
      - proxy
    depends_on:
      - webapi
