version: "3.9"

name: forecast-production

include:
  - ../common/db-compose.yaml
  - ../common/redis-compose.yaml
  - ../common/pgadmin-compose.yaml
  - ../common/caddy-compose.yaml

services:
  api:
    image: birzgalisn/forecast-api:main
    environment:
      - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
      - DB_CONNECTION_STRING=$DB_CONNECTION_STRING
      - REDIS_CONNECTION_STRING=$REDIS_CONNECTION_STRING
    networks:
      - db_net
      - redis_net
      - proxy_net
    depends_on:
      - db
      - redis

  client:
    image: birzgalisn/forecast-client:main
    environment:
      - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
    networks:
      - proxy_net
    depends_on:
      - api
