version: "3.9"

volumes:
  db:

networks:
  db_net:

services:
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db_net
