version: "3.9"

volumes:
  pgadmin:

services:
  pgadmin:
    image: dpage/pgadmin4:8.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - db_net
      - proxy_net
