version: "3"

name: forecast-staging

volumes:
  db:
  pgadmin:
  caddy_data:
  caddy_config:

networks:
  db_net:
  proxy_net:

services:
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db_net

  pgadmin:
    image: dpage/pgadmin4:8.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - db_net
      - proxy_net
    depends_on:
      - db

  api:
    image: forecast/api:staging
    build:
      context: ../../api
      dockerfile: ./Dockerfile
      args:
        - DB_CONNECTION_STRING=$DB_CONNECTION_STRING
        - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
    environment:
      - DB_CONNECTION_STRING=$DB_CONNECTION_STRING
      - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
    networks:
      - db_net
      - proxy_net
    depends_on:
      - db

  client:
    image: forecast/client:staging
    build:
      context: ../../client
      dockerfile: ./Dockerfile
      args:
        - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
        - NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
        - NEXT_PUBLIC_OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
    environment:
      - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
    networks:
      - proxy_net
    depends_on:
      - api

  caddy:
    image: caddy:2.7.6
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CNAME=$CNAME
    networks:
      - proxy_net
    depends_on:
      - client
      - api
      - pgadmin
