version: "3.9"

name: forecast-staging

include:
  - ../common/db-compose.yaml
  - ../common/redis-compose.yaml
  - ../common/pgadmin-compose.yaml
  - ../common/caddy-compose.yaml

services:
  api:
    image: forecast/api:staging
    build:
      context: ../../api
      dockerfile: ./Dockerfile
    environment:
      - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
      - DB_CONNECTION_STRING=$DB_CONNECTION_STRING
      - REDIS_CONNECTION_STRING=$REDIS_CONNECTION_STRING
    networks:
      - db_net
      - redis_net
      - proxy_net
    depends_on:
      - db

  client:
    image: forecast/client:staging
    build:
      context: ../../client
      dockerfile: ./Dockerfile
      args:
        - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
        - NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
        - NEXT_PUBLIC_OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
    environment:
      - OPEN_WEATHER_API_KEY=$OPEN_WEATHER_API_KEY
    networks:
      - proxy_net
    depends_on:
      - api
